#!/usr/bin/env bash
# Script to ping a host 5 times and show usage if no argument is passed

if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# the ip we get
target=$1


ping -c 5 "$target"
